### ISSUE TITLE
这是什么情况？出现卡顿，时刻下拉。

### ISSUE THREAD

**Issue by cddsgtc** [mescroll/mescroll#190]
1. 我给mescroll类添加了高度
2. 设置了up.isBoth:false

环境： 
* vue@2.5
* mescroll@1.3.8

`jade`
```pug
.scroll-box.mescroll(ref="scroll" :class="{'not-in-app':situationType != 1}")
```
`scss`
```scss
.scroll-box,
  .mescroll {
    padding-bottom: 0.1rem;
    height: calc(100vh - 1rem);
    width: 100vw;
  }
```
`js`
```js
 // 初始化上拉加载
    mescrollInit() {
      this.mescroll = new Mescroll(this.$refs.scroll, {
        up: {
          callback: this.controlRecommend,
          page: {
            num: 0,
            size: 10
          },
          noMoreSize: 5,
          isBoth: false
        }
      })
    },
```

然后就这样了。。
![screencast-173 16 97 142-3031-2018 12 06-16-02-26](https://user-images.githubusercontent.com/16315661/49570181-f234cc80-f970-11e8-965a-6fcc4c929386.gif)
